server:
  host: 0.0.0.0
  port: 8080
application:
  name: lotto

profiles:
  dev:
    greeting: "Hello, Dev!"
    server:
      port: 8080
    color:
      - red
      - blue
    price:
      won: 1000
      dolor: 1
  prod:
    greeting: "Hello, Production!"
    server:
      port: 8090
    color:
      - red
      - blue
    price:
      won: 2000
      dolor: 2
