name: check variables

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      profile:
        description: input profile for build and runtime
        type: string
        default: "dev"
        required: true

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    environment:
      name: SimplyDemo
      url: https://github.com
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      REPOSITORY_URL: ${{ vars.REPOSITORY_URL }}

    steps:
      - name: check variables
        run: |
          printf 'GITHUB_RUN_NUMBER: %s\n' "$GITHUB_RUN_NUMBER"
          printf 'AWS_REGION 1: %s\n' "$AWS_REGION"
          printf 'AWS_REGION 2: %s\n' "${{env.AWS_REGION}}"

      - name: step-1 initialize variables
        run: |
          echo "version=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: step-2 use variables
        run: |
          printf 'version: %s\n' "$version"
          printf 'AWS_REGION: %s\n' "$AWS_REGION"
          printf '%s\n' "$REPOSITORY_URL"
          printf 'GITHUB_RUN_NUMBER: %s\n' "$GITHUB_RUN_NUMBER"

      - name: step-3 echo
        run: |
          echo "version: $version"
          echo "AWS_REGION: $AWS_REGION"
          echo "REPOSITORY_URL: $REPOSITORY_URL"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
