name: check variables

env:
  AWS_REGION: 'ap-northeast-1'

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      profile:
        description: input profile for build and runtime
        type: string
        default: "dev"
        required: true

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    environment:
      name: SimplyDemo
      url: https://github.com

    steps:
      - name: show variables
        run: |
          - echo "AWS_REGION 1: $AWS_REGION"
          - echo "AWS_REGION 2: ${AWS_REGION}"
          - echo "AWS_REGION 3: ${{ env.AWS_REGION }}"
          - echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          - echo "REPOSITORY_URL: ${REPOSITORY_URL}"
