name: check variables

env:
  AWS_REGION: 'ap-northeast-1'

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      profile:
        description: input profile for build and runtime
        type: string
        default: "dev"
        required: true

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    environment:
      name: SimplyDemo
      url: https://github.com

    steps:
      - name: show variables
        run: |
          echo "version=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "AWS_REGION=${AWS_REGION}" >> $GITHUB_ENV
          echo "REPOSITORY_URL=${REPOSITORY_URL}" >> $GITHUB_ENV
